### ISSUE TITLE
Please remove

### ISSUE THREAD

**Issue by phated** [liufei/gulp-docs#2]
Gulp now has official docs at https://gulpjs.com/docs/en/getting-started/quick-start and your docs are confusing our users.  Will you please remove these docs?  It'd be awesome if the domain could redirect to our website.

**Comment by liufei** [comment]
> Gulp now has official docs at https://gulpjs.com/docs/en/getting-started/quick-start and your docs are confusing our users. Will you please remove these docs? It'd be awesome if the domain could redirect to our website.

@phated As a gulp user, I really appreciate your great work on gulp. This project was created for better reading experience of gulp docs. I'm so glad to see that there is an official one. How about transferring the domain of gulpjs.org to you? Then you can do whatever you want.

**Comment by phated** [comment]
@liufei that would be great!  Can you transfer it to the gulp team email (team@gulpjs.com)?

**Comment by phated** [comment]
@liufei are you still willing to transfer the domain to the gulp team so we can redirect it to our new docs?

**Comment by liufei** [comment]
@phated Sorry for the late reply. I'm on my annual leave during these days. I have retrieved the authorization EPP code. What should I do next?

**Comment by phated** [comment]
@liufei I just talked to @contra and he's going to take care of it.  Can you email the EPP to him at yo@contra.io

**Comment by liufei** [comment]
@phated Already sent. Thanks for you great work on Gulp.

**Comment by phated** [comment]
Thanks @liufei!
